model = "gpt-5.5"
model_reasoning_effort = "medium"
model_context_window = 900000
model_auto_compact_token_limit = 800000

# Segurança / padrão
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "live"
personality = "pragmatic"
plan_mode_reasoning_effort = "medium"
approvals_reviewer = "guardian_subagent"

[profiles.pm]
sandbox_mode = "workspace-write"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "concise"
model_instructions_file = "~/.codex/prompts/pm.md"

[profiles.arq]
model = "gpt-5.4"
sandbox_mode = "workspace-write"
model_reasoning_effort = "xhigh"
model_instructions_file = "~/.codex/prompts/architect.md"

[profiles.dev]
sandbox_mode = "workspace-write"
model_reasoning_effort = "xhigh"
model_instructions_file = "~/.codex/prompts/dev.md"

[profiles.qa]
sandbox_mode = "read-only"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "concise"
model_verbosity = "low"
model_instructions_file = "~/.codex/prompts/reviewer.md"

[projects."/home/raivitor/gitlab/shiva-remessas"]
trust_level = "trusted"

[projects."/home/raivitor/.codex"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/boilerplate-2026"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/cestinha-de-supermercado"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/dream-finder"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/gerenciador-de-anuncios-de-aluguel"]
trust_level = "trusted"

[projects."/home/raivitor/gitlab/safra"]
trust_level = "trusted"

[projects."/home/raivitor/gitlab/safra/frontend-painel-adm"]
trust_level = "trusted"

[projects."/home/raivitor/gitlab/safra/backend-gateway"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/english-study"]
trust_level = "trusted"

[projects."/home/raivitor/gitlab/siga"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/cms-rua-larga"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/ai-translate"]
trust_level = "trusted"

[projects."/home/raivitor/projeto/estudo-anki"]
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true
writable_roots = ["."]
exclude_slash_tmp = true
exclude_tmpdir_env_var = true

[otel]
exporter = "none"
trace_exporter = "none"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.openaiDeveloperDocs.tools.search_openai_docs]
approval_mode = "approve"

[mcp_servers.openaiDeveloperDocs.tools.fetch_openai_doc]
approval_mode = "approve"

[features]
apps = true
terminal_resize_reflow = true

[tui]
status_line = ["model-with-reasoning", "context-remaining", "project-root", "git-branch", "context-used", "five-hour-limit", "context-window-size", "fast-mode"]
theme = "catppuccin-macchiato"

[tui.model_availability_nux]
"gpt-5.5" = 4

[notice]
hide_rate_limit_model_nudge = true
fast_default_opt_out = true

[plugins."github@openai-curated"]
enabled = true

[hooks.state]
